print("calcuator for volume of curved shapes")
print("the values of r & h must be in same unit")
print("the unit of vo;umes are the cube of the unit provided, examples:- cm^3, m^3,etc")
import cmath
r=input("enter the radius r =")
h=input("enter the height h =")
vs=((3.14)*(4)*(float(r)**3)/(3))
vc=((3.14)*float(h)*(float(r)**2)/(3))
vcy=((3.14)*float(h)*(float(r)**2))
print("the volume of a sphere with radius r and height h =",vs)
print("the volume of a cone with radius r and height h =",vc)
print("the volume of a cylinder with radius r and height h =",vcy)
print("the ratio between volume of sphere and cone is :",(float(vs)/float(vc)))
print("the ratio between volume of cone and cylinder is :",(float(vc)/float(vcy)))
print("the ratio between volume of cylinder and sphere is :",(float(vcy)/float(vs)))
print("the relation between volumes of sphere, cone and cylinder is given below :-")
r1=12*float(r)
r2=float(h)
r3=3*float(h)
print("relation is :-",r1,":",r2,":",r3)