# input function always gives strong values to use the input function in doing in calculations
# we have to typecast it into numerical variable
print("basic use of input function")
a=input()
print(a)
print("2nd use of input function")
a1=input()
print("my name is ",a1)
print("3rd use of input function")
b=input("enter your name:")
print("my name is",b)
print("using input function to enter numbers")
x=input("enter first number:")
y=input("enter second number:")
print(int(x)+int(y))
print("concatination in input function")
a2=input("enter first name:")
b1=input("enter second name:")
print(a2+b1)
# we can diretly type cast the in put function as shown below
a3=float(input("enter your number:"))
print(a3 + int(x))